version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodatabase
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: rgbcolors
    volumes:
      - dbdata6:/data/db
      - dbconfig6:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  dbdata6:
  dbconfig6:
