server:
  port: 8081

spring:
  application:
    name: spring-security-openid-demo
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-boot-client
            client-secret: uONWUQcZBfmTXgUM4AoOD0fUSSDIa14r
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:7080/realms/dev
